Waiter and small new test
24alinka/pythonProject1 pull request #4
Opened 2022-09-25 07:51 UTC by 24alinka

Hello. I added some new tests and added a waiter. I'm also trying to add tests to the new Chat page. But so far it hasn't come out. I have a problem with my tests on the "Start page", they worked before adding the Chat page, but now they don't. Could you please check what is the problem?

2022-09-26 08:59 UTC, QALightLecorPython requested changes

2022-09-26 08:59 UTC, QALightLecorPython commented on tests/test_chat_page.py
> +        yield TestChatMessage(driver)
Don't know what you're trying to do, but this won't work. 
When you're getting the BASE_URL you're on StartPage, not ChatPage or any other page.
Chat by itself is not the Page it's an element like Header, so it should be implemented in same way.

2022-09-26 09:00 UTC, QALightLecorPython commented
>  I have a problem with my tests on the "Start page", they worked before adding the Chat page, but now they don't. Could you please check what is the problem? 

I cannot check what is the problem. You could investigate it and describe it to me, so I can help you with the solution.

2022-09-26 18:47 UTC, 24alinka commented
Hello. I fixed some tests. But I have issues with all my tests. I think it has to do with imports. Could you recheck and tell me what needs to be fixed?

2022-09-27 10:01 UTC, QALightLecorPython requested changes

2022-09-27 10:01 UTC, QALightLecorPython commented on pages/header.py
> +        self.hello_page = HelloPage(self.driver)
HelloPage is not a part of the header. Header is the part of the hello page ;)

2022-09-27 10:01 UTC, QALightLecorPython commented on pages/header.py
> +    def sign_in(self, username, password):
This is actually related to the start page not to the header

2022-09-27 10:01 UTC, QALightLecorPython commented on pages/start_page.py
> +        # self.hello_page = HelloPage(self.driver)
Hello page is not part of the start page. This is a different page

2022-09-27 10:01 UTC, QALightLecorPython commented on pages/header.py
> +from pages.hello_page import HelloPage
Do not use global imports for pages

2022-10-03 15:09 UTC, closed without merging